document.addEventListener("DOMContentLoaded", function () {
    // 1. Load the official Ko-fi script dynamically
    const kofiScript = document.createElement('script');
    kofiScript.src = 'https://storage.ko-fi.com/cdn/widget/Widget_2.js';
    
    kofiScript.onload = function () {
        if (typeof kofiwidget2 !== 'undefined') {
            // Initialize the Ko-fi widget settings
            kofiwidget2.init('Support the Project with a Ko-fi', '#e9166a', 'L2J723MSF6');
            
            // Get the HTML markup generated by Ko-fi
            const kofiHTML = kofiwidget2.getHTML();
            
            // 2. Inject into Header
            const headerContainer = document.querySelector('.header-kofi-button');
            if (headerContainer) {
                headerContainer.innerHTML = kofiHTML;
            }
            
            // 3. Inject into Footer
            const footerContainer = document.querySelector('.footer-kofi-button');
            if (footerContainer) {
                footerContainer.innerHTML = kofiHTML;
            }
        }
    };
    
    document.body.appendChild(kofiScript);
});